name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Compile
      run: msbuild lame.sln /p:Configuration=Release /p:Platform=x64

    - name: Save EXE
      uses: actions/upload-artifact@v4
      with:
        name: my-exe-file
        path: |
          **/Release/**/*.exe
          **/x64/Release/**/*.exe
